### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by Pictor13** [ccampbell/xtab#10]
I started to use the extension today and I got some thoughts about how I would personally improve its functionalities.
Here are some feature suggestions:

- allow to disable block/extension; or allow to specify 0/null as value to disable the functionality (now everything lower than 1 is just working the same)

- allow per-window setting, and an option to switch the functionality from global to per-window (maybe allow to specify a global max number of tabs regardless of what window they are located)

- add setting to not close audio and/or pinned tabs

- add notification/reminder of blocked tabs (for when opening links from outside the browser and the tab gets shut down)

- allow to replace/load a tab (least accessed/used/etc) instead of closing it (so one can use history to recover the previous content)

- ensure the extension works with other famous ones (e.g. restoring tabs from OneTab, without loosing tabs in case the restored ones are more than the xtab limit)

I still have to check the repository code, but could be that if I get time then I will implement some of them and create pull requests.
This issue is more a reminder than a request.

**Comment by ccampbell** [comment]
Hi @Pictor13 I appreciate you taking the time to make this issue. I just rearchitected and rewrote xTab and released version 1.0.0. It is going to be a slow rollout, but it is available in the [Chrome Web Store](https://chrome.google.com/webstore/detail/xtab/amddgdnlkmohapieeekfknakgdnpbleb) to try.

Version 1.0.0 implements a bunch of the features you suggested. Will touch on each briefly.

> allow to disable block/extension; or allow to specify 0/null as value to disable the functionality (now everything lower than 1 is just working the same)

This is an interesting idea, but there are already two ways to do this. You can use the default Chrome extension behavior by right clicking -> Selecting “Manage Extensions” and then turning it off. You can also set the limit temporarily to some very high number so that nothing happens. I haven’t personally felt the need to toggle it on and off, but perhaps it may be added in the future.

> allow per-window setting, and an option to switch the functionality from global to per-window (maybe allow to specify a global max number of tabs regardless of what window they are located)

This is implemented behind a flag version 1.0.0, but it is not exposed in the UI. Default behavior is maximum limit per window vs. globally. I may expose it in a future version.

> add setting to not close audio and/or pinned tabs

A setting has been added for whether to close audible tabs or not. As of version 1.0.0, pinned tabs and audible tabs will not be closed by default. I do not want to add a setting for pinned tabs because by there nature I believe if you pin something you do not want it to be closed.

> add notification/reminder of blocked tabs (for when opening links from outside the browser and the tab gets shut down)

This is implemented at least somewhat in the new version. It will show a message when you try to open a tab beyond your limit. (There is a setting to disable it and use the old behavior of blocking immediately).

![xtabclose](https://user-images.githubusercontent.com/259316/55255585-64d3fb80-5231-11e9-8c56-da5cfbd14188.gif)

> allow to replace/load a tab (least accessed/used/etc) instead of closing it (so one can use history to recover the previous content)

This is implemented in the new version as well (disabled by default):

![xtabrecycle](https://user-images.githubusercontent.com/259316/55255639-7f0dd980-5231-11e9-8969-532ea5b43cf2.gif)

> ensure the extension works with other famous ones (e.g. restoring tabs from OneTab, without loosing tabs in case the restored ones are more than the xtab limit)

I am not sure this is actually possible since xTab depends on the browser events themselves, and if you restore a large session from OneTab, I don’t think it is possible to detect.

---

I am going to close this issue, but feel free to make others if you have other suggestions/features/ideas. From 1.0.0 on I plan on continuing development in private, and I haven’t decided if I will make the new code open source or not.
