### ISSUE TITLE
Reuse old tab instead of opening new

### ISSUE THREAD

**Issue by vitalyster** [ccampbell/xtab#2]
Is it possible to reuse old tab when I hit limit and open new link in that tab, with ability to "go back"?
Old versions of Safari/iOS with tab limit have this behavior.

**Comment by ccampbell** [comment]
This functionality has been added in version 1.0.0 of the extension. I am doing a slow rollout, but you can manually install it from the Chrome web store if you would like to try it.

The recycle functionality is disabled by default since I would say it is a bit experimental, and it hasn’t been extensively tested, but you can enable it:

![xtab](https://user-images.githubusercontent.com/259316/55254245-c2fedf80-522d-11e9-807d-8155a52ac771.gif)
