### ISSUE TITLE
Warn before closing or allow a undo

### ISSUE THREAD

**Issue by nikolay** [ccampbell/xtab#9]
By installing this extension, you closed 10s of my tabs without warning me. You should have an "Undo" option as I've lost a lot of work!

**Comment by vilie** [comment]
How would the "undo" be implemented with preserving the maximum tab numbers? Closing the newsest tab you just opened?

**Comment by ccampbell** [comment]
I apologize for any inconvenience during the installation, but it has to start somewhere. 

If someone has 50 tabs open then installs xTab and it does not touch those 50 tabs, they will think that the extension doesn’t work. In any case, [version 1.0.0](https://chrome.google.com/webstore/detail/xtab/amddgdnlkmohapieeekfknakgdnpbleb) offers a recycle functionality where instead of closing old tabs it will reuse an old tab which means previous pages will be preserved in the browser history.

![xtabrecycle](https://user-images.githubusercontent.com/259316/55255071-0a866b00-5230-11e9-9f92-2781854f5360.gif)

It is not enabled by default, but you can enable it and try it. Occasionally you will notice a flash like in the gif since it has to reuse a tab that is already open.
